Space Saver Hub Project
AlyAtalla/React-Group-Project pull request #33
Opened 2023-08-31 16:54 UTC by coker2019

-Config & basic setup.

-Redux: Fetch data and update redux store.

-Render UI: lists.

-Write actions and reducers for canceling rockets/dragons and leaving missions.

- Add test to components.

2023-08-31 18:03 UTC, frank1738 requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/W3dGGNpaeOt3KcUWr2/giphy.gif"/>

## Highlights


✅ Great work using  React Testing Library to test proper rendering👍 
✅ Good work setting up redux correctly👍



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 18:03 UTC, ghost commented on src/_test_/RocketItem.test.js
> +});
- [ ] 🎉 Great job on thoroughly testing for proper rendering! 👍 Don't forget the importance of testing your pure functions too. 🧪 Ensuring your app behaves as expected is the key! Keep up the awesome work in this PR! 🚀

2023-08-31 18:03 UTC, ghost commented on src/redux/Rocket/rocketSlice.js
> +});
- [ ] I've observed that when I book a rocket 🚀 and then navigate to the profile page 🧑‍🚀, the booking is correctly added there. However, upon returning to the rockets page 🪐, the booking disappears, which is not the expected behavior. 🤔 Please refer to your missions implementation to achieve consistent behavior for rocket bookings. Keep up the good work! 💪🌟

2023-09-01 11:29 UTC, skyv26 approved these changes
## Hi @AlyAtalla and @coker2019, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMDJhMjgwMDkxOGE3NjA4MjIzYTVjYmExMTFiNmUxYjgxN2FlN2U5NCZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PXM/FEzcI0TlDxkdbaHTwV/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Nice *UI* design ✅ 
- Professional `README` template ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 11:44 UTC, merged